# Volatility of Cryptocurrencies

## Data Preparation
Daily Data of Most traded Cryptocurrencies:

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#setting figure size
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 20,10

import datetime as dt
import os
import pandas_datareader.data as web

tickers= ['USDT-USD', 'BTC-USD', 'ETH-USD', 'XRP-USD', 'LTC-USD', 'BCH-USD', 'EOS-USD', 'LINK-USD', 'ADA-USD', 'XMR-USD']
start= dt.datetime(2018,12,31)
end= dt.datetime(2020,12,31)

def compile(tickers, start, end):
  main_df=pd.DataFrame()
  for count,ticker in enumerate(tickers):
    df= web.get_data_yahoo(ticker, start, end, interval='d')
    if not os.path.exists('Cryptocurrencies'):
        os.makedirs('Cryptocurrencies')
    df.to_csv('Cryptocurrencies/{}.csv'.format(ticker))

df = compile(tickers, start, end)

### Close price of cryptocurrencies

In [ ]:
for count,ticker in enumerate(tickers):
  if ticker=='USDT-USD':
    data = pd.read_csv('Cryptocurrencies/{}.csv'.format(ticker), index_col='Date', parse_dates=True)
    data.drop(['High','Low','Open','Adj Close','Volume'], axis=1, inplace= True)
    data.rename(columns={'Close': ticker}, inplace=True)
  else:
    data_count = pd.read_csv('Cryptocurrencies/{}.csv'.format(ticker), index_col='Date', parse_dates=True)
    data_count.drop(['High','Low','Open','Adj Close','Volume'], axis=1, inplace= True)
    data_count.rename(columns={'Close': ticker}, inplace=True)
    data = pd.concat([data, data_count], axis=1)
data.to_csv('Cryptocurrencies/data_Close.csv')
data.head()

            USDT-USD      BTC-USD     ETH-USD  ...  LINK-USD   ADA-USD    XMR-USD
Date                                           ...
2018-12-31  1.013722  3742.700439  133.368256  ...  0.289444  0.041063  46.228168
2019-01-01  1.018335  3843.520020  140.819412  ...  0.299371  0.042547  48.367496
2019-01-02  1.024012  3943.409424  155.047684  ...  0.316489  0.045258  52.252449
2019-01-03  1.019473  3836.741211  149.135010  ...  0.365974  0.042682  49.815357
2019-01-04  1.017200  3857.717529  154.581940  ...  0.437175  0.043812  50.630875

[5 rows x 10 columns]

### Volume and Close Cryptocurrencies

In [ ]:
for count,ticker in enumerate(tickers):
  if ticker=='USDT-USD':
    data1 = pd.read_csv('Cryptocurrencies/{}.csv'.format(ticker), index_col='Date', parse_dates=True)
    data1.drop(['High','Low','Open','Adj Close'], axis=1, inplace= True)
    data1.rename(columns={'Close': ticker, 'Volume':'Vol_{}'.format(ticker)}, inplace=True)
  else:
    data1_count = pd.read_csv('Cryptocurrencies/{}.csv'.format(ticker), index_col='Date', parse_dates=True)
    data1_count.drop(['High','Low','Open','Adj Close'], axis=1, inplace= True)
    data1_count.rename(columns={'Close': ticker, 'Volume':'Vol_{}'.format(ticker)}, inplace=True)
    data1 = pd.concat([data1, data1_count], axis=1)
data1.to_csv('Cryptocurrencies/data_Vol_Close.csv')
data1.head()

            USDT-USD  Vol_USDT-USD  ...    XMR-USD  Vol_XMR-USD
Date                                ...
2018-12-31  1.013722  3.447514e+09  ...  46.228168   11899404.0
2019-01-01  1.018335  3.139235e+09  ...  48.367496   10174528.0
2019-01-02  1.024012  4.442755e+09  ...  52.252449   24331239.0
2019-01-03  1.019473  3.487203e+09  ...  49.815357   12738595.0
2019-01-04  1.017200  3.895787e+09  ...  50.630875   12125339.0

[5 rows x 20 columns]

### Calculate Return

In [ ]:
df_USDT = pd.read_csv('Cryptocurrencies/USDT-USD.csv', index_col='Date', parse_dates=True)
df_USDT.drop(['High','Low','Open', 'Close'], axis=1, inplace= True)
df_USDT.head()

                  Volume  Adj Close
Date
2018-12-31  3.447514e+09   1.013722
2019-01-01  3.139235e+09   1.018335
2019-01-02  4.442755e+09   1.024012
2019-01-03  3.487203e+09   1.019473
2019-01-04  3.895787e+09   1.017200

In [ ]:
df_USDT.tail()

                  Volume  Adj Close
Date
2020-12-28  7.675704e+10   0.998603
2020-12-29  7.679262e+10   0.998590
2020-12-30  7.266696e+10   1.000275
2020-12-31  6.146846e+10   1.000598
2021-01-01  6.050999e+10   1.001916

In [ ]:
df_USDT_returns = 100*(np.log(df_USDT['Adj Close']).pct_change())
df_USDT_returns = pd.DataFrame(df_USDT_returns)
df_USDT_returns.rename(columns={'Adj Close': 'lreturn_pct'},inplace= True)
df_USDT_returns['Volume'] = df_USDT['Volume']
USDT = df_USDT_returns.iloc[1:-1].to_csv('Cryptocurrencies/USDT.csv')
df_USDT_returns.iloc[1:-1].tail(6)

            lreturn_pct        Volume
Date
2020-12-26 -1005.128377  7.024933e+10
2020-12-27   -24.569706  9.526486e+10
2020-12-28    21.916808  7.675704e+10
2020-12-29     0.930770  7.679262e+10
2020-12-30  -119.488132  7.266696e+10
2020-12-31   117.390136  6.146846e+10